name: Build and Upload Wheel

on:
  push:
    branches: [ generator-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build wheel
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pygen-wheel
          path: dist/*.whl
