name: Generate Python Code from Config - Unique Run

on:
  workflow_dispatch:
  push:
    paths:
      - 'configs/**'
      - '.github/workflows/generate-code.yml'
      - 'generate_code.py'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download pygen wheel from generator-branch
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-wheel.yml
          workflow_conclusion: success
          branch: generator-branch
          name: pygen-wheel
      - name: Install pygen wheel
        run: |
          pip install dist/*.whl
      - name: Generate Python code from config
        run: |
          python -c "from pygen.generator import generate_code; generate_code('configs/config.json')"
      - name: Commit and push generated file to main branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout main
          git add generated/*.py
          git commit -m "Add generated Python file [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
